blogger/config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'
resources :articles do 
	resources :comments
	
end
resources :tags
end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	def tag_list
		tags.join(", ")
	end
		
	
	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
 		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
	def to_s
		name
		
	end
end

blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
		
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end
	def new
		@article = Article.new
	end
	def create
		@article = Article.new(article_params)

		@article.save
		flash.notice = "blogging '#{@article.title}' created"
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash.notice = "blogging '#{@article.title}' deleted"
		redirect_to articles_path
		
	end
	def edit
		@article = Article.find(params[:id])
		
	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "blogging '#{@article.title}' updated"
		redirect_to article_path(@article)
		
	end



	private

	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
		
	end
end
 

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]

		@comment.save

		redirect_to article_path(@comment.article)
		
	end
def comment_params
	params.require(:comment).permit(:author_name, :body)
	
end
end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
		
	end
	def index
		@tags = Tag.all
		
	end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div>
	<blockquote>
	
	<p><%= comment.body %></p>
	<h6> comment by <%= comment.author_name %> posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later </h6>

	</blockquote>
</div>

blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
		<li><%= error %> </li>
		<% end %>
	</ul>

	<p>
		<%= f.label :title %> <br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<%= f.text_field :body%>
	</p>
	<p>
		<%= f.label :tag_list, "tags" %>
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<% if @article.image.exists? %>
			<%= image_tag @article.image.url%>
			<% end -%>
		<%= f.label :image, "add a pic" %>
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>

blogger/app/views/articles/edit.html.erb
<h1> Edit <strong>Dis</strong> Bloggings</h1>
<%= render partial: 'form'%>

blogger/app/views/articles/index.html.erb
<div class="wrapper style2"><h1> <strong>Deez</strong> Bloggings</h1>
</div>
<div class="wrapper style2">
<ul class="alt">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>

    </li>
  <% end %>
  </ul>
  </div>
<br>
  <%= link_to "make a new blogging", new_article_path, class: 'button fit' %>

blogger/app/views/articles/new.html.erb
<div class="wrapper style2">
<h1> Make New Bloggings </h1>

<%= render partial: 'form'%>
	</div>

<%= link_to "back to the bloggings", articles_path, class: "button fit" %>

blogger/app/views/articles/show.html.erb
<div class="wrapper style2">
<div class="wrapper style2">
<h1> <%= link_to @article.title, article_path %> </h1>
<p><%if @article.image.exists?%>
<%= image_tag @article.image.url %></p>
<% end -%>
<article class=""><%= @article.body %></article>
<code>
	tags:
	<% @article.tags.each do |tag| %>
	<%= link_to tag.name, tag_path(tag) %>
	<% end -%>
</code>></div>
<%= link_to "delete dis bloggings", article_path(@article), method: :delete,data:{confirm: "you're deleting me bruh?"}, class: "button  small" %>
<%= link_to "edit dis bloggings", edit_article_path(@article), class: "button small" %>
<br>


<div class ="wrapper style2">
<h3> comments (<%= @article.comments.size %>) </h3>
<%= render partial: 'articles/comment', collection: @article.comments %>


</div>
</div>
<%= render partial: 'comments/form'%>

<%= link_to "back to the bloggings", articles_path, class: "button fit" %>

blogger/app/views/comments/_form.html.erb
	<h4>
		Comment Dis Blogging
	</h4>
	<%= form_for [ @article, @comment] do |f| %>
	<p><%= f.text_field :author_name %></p>
	<p> <%= f.label :author_name, "^^your name" %> </p><br>
	<p><%= f.text_field :body %></p>
<p> <%= f.label :body, "^^your comment" %> </p><br>
	

	<button><%= f.submit %></button>
<% end %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<hr > <%= flash.notice %></hr>
</body>
</html>

blogger/app/views/tags/index.html.erb
<div class="wrapper style2"><h1> <strong>Deez</strong> Taggings</h1>
</div>
<div class="wrapper style2">
<ul class="alt">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>

    </li>
  <% end %>
  </ul>
  </div>
  <%= link_to "back to the bloggings", articles_path, class: "button fit" %>

blogger/app/views/tags/show.html.erb
<div class="wrapper style2">
<h2>bloggings with <strong>dis</strong> tag</h2>
</div>
<ul class="alt">
	<% @tag.articles.each do |article|%>
	<li><%= link_to article.title, article_path(article)%></li>
	<% end -%>	
</ul>
<p><%= link_to "list all the taggings", tags_path%></p>
<div class="wrapper style2">
<%= link_to "back to the bloggings", articles_path, class: "button fit" %>
</div>